### ISSUE TITLE
Falsche Abholtermine für gelber Sack

### ISSUE THREAD

**Issue by uescher** [opendata-stuttgart/meinsack#6]
Keine Ahnung ob der Service noch gemaintained wird. Falls ja dann folgendes issue:
Diese beiden Quellen liefern unterschiedliche Termine
http://www.stuttgart.de/img/mdb/item/7409/120960.pdf
https://meinsack.click/v1/70327/Ulmer%20Stra%C3%9Fe/

**Comment by mfa** [comment]
schaal-mueller hat die api abgeschaltet.
wir werden einen weg finden das zu fixen.
